- src/components/Dropdown/Dropdown.tsx
> DD-8-Dropdown
> placeholder 에러 수정
> 조그만 에러 하나 수정했습니다. 코드리뷰 없어도...좋아요..!
> 🐛fix: placeholder오류 수정

- src/components/Post/Post.tsx
- src/components/Post/PostCard.tsx
- src/types/Notice.d.ts
- src/types/Shop.d.ts
> DD-47
> 데이터 정말 다양한 스타일로 들어오네여 이번 프로젝트에서 마니배울수잇을거같아여 
Link컴포넌트 없애서 밖에서 설정해줘야댑니다 
(href를 따로 받을 수도 있긴할텐데 컴포넌트 취지랑도 안맞고 굳이 프롭스를 하나 추가하는 느낌이라 뺐어요!)
> 🐛fix: hotfix/Post 컴포넌트 데이터 타입 재설정

- src/components/Post/Post.tsx
- src/components/Post/PostCard.tsx
- src/components/pageComponents/NoticeDetail/ApplicantsList.tsx
- src/components/pageComponents/NoticeDetail/NoticeDetailCard.tsx
- src/components/pageComponents/NoticeDetail/NoticeDetailCardButton.tsx
- src/components/pageComponents/NoticeDetail/NoticeDetailModals.tsx
- src/components/pageComponents/NoticeDetail/RecentNoticeListSection.tsx
- src/components/pageComponents/NoticeDetail/index.tsx
- src/hooks/useRecentWatchedNotices.ts
- src/pages/shops/[shop_id]/notices/[notice_id]/index.tsx
> #DD26
> 지금까지 작업가능한 부분 거의다 해놨는데 (완성은 아니구)
PR올려놓으면 조언을 들을 수 있을까 ... 해서 올려놓습니다......
파일체인지에 잘못된것들있는데 나중에 수정해놓을게요
> ✨feat: notice detail page(공고상세페이지, 1차)

- src/components/Table/EmployerTable.tsx
- src/components/Table/EmployerTableBody.tsx
- src/components/Table/EmployerTableHeader.tsx
DD-60-Fix-EmployerTable
- 받는 데이터의 타입과 내용이 잘못 연결된 부분 수정
- 테이블 헤더와 바디를 컴포넌트로 만들어서 분리
> fix: EmployerTable 데이터 수정, 컴포넌트 분리

- src/lib/utils/Icons.tsx
> fix: 배포 오류 수정

- src/components/pageComponents/LoginSignUp/LoginSignUp.tsx
- src/components/pageComponents/LoginSignUp/MemberTypeToggle.tsx
- src/components/pageComponents/LoginSignUp/SignInForm.tsx
- src/components/pageComponents/LoginSignUp/SignInFormContainer.tsx
- src/components/pageComponents/LoginSignUp/SignUpFormContainer.tsx
> Dd 63 refactor login signup
최대한 노력했습니다..
> ♻️refactor: loginSignup 리팩토링

- src/components/Filter/DateSection.tsx
- src/components/Filter/Filter.tsx
> Dd 68 fix filter
날짜 나오는 부분 로직 변경했습니다
초기화 누르면 검색결과도 같이 초기화 하게 했고 이전날짜 선택 못하게 바꿨습니다.
> 🐛fix: Filter 로직 변경

- src/pages/shops/[shop_id]/index.tsx
> DD-69-fix: 가게데이터가 없을때 로직 수정
미안합니다 너무 못만들어서 fix나 refactor pr을 자주 올리게 되네요 ㅠㅠ 열심히하겠습니다
> 🐛fix: shopDetail 가게 정보 페이지 로직 수정

- src/pages/index.tsx
DD-66-feat-integrate-filter-with-main-page
- fetchFilterData 함수에 noticeAPI.getNoticeList() 적용
- 메인 페이지에서 상태 값으로 만들어 필터된 리스트 랜더링
> feat: 필터컴포넌트의 기능 메인페이지 연결 (#66)

- src/components/Button/Button.tsx
> 🐛fix: disable, able 변경

- src/components/Modal/ModalCustom.tsx
- src/components/Modal/ModalPrimary.tsx
- src/components/Modal/ModalWrapper.tsx
-prop autoClose(boolean)으로 조절됩니다
> #DD-51
> 간단한 작업인데 .. 늦게했ㅅ브니다.. 죄송하고 .. autoClose 프롭으로 백그라운드 클릭시 모달을 닫히게 할지 조절할 수 있어요
옵셔널 프롭으로 추가하고 기본값줘서 기존에 사용하던 코드에서 변화없이 사용가능합니다!! 
> ✨feat: 모달 백그라운드 클릭시 자동 닫힘 기능추가

- src/components/Pagination/Pagination.tsx
(#76)
DD-76-refactor-enlarge-pagination-click-area
- 페이지네이션 숫자 버튼에만 클릭 영역이 해당해서 주위 영역으로 확대하고 호버 효과 추가하여 클릭 가능한 상태임을 나타냄
> DD-76-refactor-enlarge-pagination-click-area

- src/components/Button/Button.tsx
- src/components/pageComponents/NoticeDetail/NoticeDetailCard.tsx
- src/components/pageComponents/NoticeDetail/NoticeDetailCardButton.tsx
- src/components/pageComponents/NoticeDetail/NoticeDetailModals.tsx
- src/constants/noticeDetailButtonMap.ts
- src/hooks/useApiRequestWithPopup.ts
- src/hooks/useApplicationActions.ts
- src/hooks/useNoticeDetailCardButton.ts
- tailwind.config.ts
> #DD-74
> 유틸함수로 작업해야할걸 커스텀훅으로까지 빼버린느낌이지만 ... 담버에 수정하겠습니다
페이지 연결이 되어야 작업하기 편하실거같아서 빠르게 머지할게여!
> ♻️refactor: 공고상세페이지 로직 분리 및 디자인 수정

- src/pages/index.tsx
(#80)
DD-80-feat-job-posting-detail-navigation
- Link 컴포넌트를 사용해서 공고 상세 페이지로 이동 기능 추가
> ✨feat: 공고 리스트에서 클릭해서 공고 상세로 페이지 이동 구현

- src/components/Table/EmployeeTable.tsx
- src/components/pageComponents/MyPage/MyPageProfile.tsx
- src/components/pageComponents/MyPage/MyPageRegistered.tsx
- src/constants/errorMessage.ts
- src/lib/api/applicationAPI.ts
DD81
1. 내 프로필 신청내역 보여주는 테이블 데이터 연결했읍니다.
2. 내 프로필 스타일 수정
3. employeetable 포맷 값 수정
> ♻️ refactor: my page table data 연결

- src/components/Badge/FilterBadge.tsx
- src/components/Badge/RateBadge.tsx
- src/components/Dropdown/Dropdown.tsx
- src/components/Filter/Filter.tsx
- src/components/Footer/footer.tsx
- src/components/Gnb/GnbButton.tsx
- src/components/Gnb/SearchBar.tsx
- src/components/Input/InputImage.tsx
- src/components/Input/InputPassword.tsx
- src/components/Modal/ModalPrimary.tsx
- src/components/NotificationModal/NotificationModal.tsx
- src/components/Pagination/Pagination.tsx
- src/components/SortDropdown/SortDropdown.tsx
- src/components/pageComponents/LoginSignUp/MemberTypeButton.tsx
- src/components/pageComponents/MyPage/MyPageProfile.tsx
- src/components/pageComponents/MyPage/MyPageRegistered.tsx
- src/components/pageComponents/ShopDetail/ShopHeader/HeaderInfo.tsx
DD86
1. 아이콘에 aria-label 추가했어요.
> ♻️ refactor: aria-label 추가

- src/components/Table/EmployerTable.tsx
- src/components/pageComponents/NoticeDetail/ApplicantsList.tsx
- src/components/pageComponents/NoticeDetail/NoticeDetailCard.tsx
- src/components/pageComponents/NoticeDetail/NoticeDetailListSection.tsx
- src/pages/shops/[shop_id]/notices/[notice_id]/index.tsx
- src/types/Application.d.ts
> #DD-88
> 브랜치 이름을. . 잘못지은듯 하네요 
> ✨feat: 공고상세페이지 지원자 목록에 페이지네이션 추가 및 공고마감시 클릭제한

- src/components/pageComponents/AddShopPage/index.tsx
- src/lib/utils/validation.ts
- src/pages/shops/[shop_id]/edit.tsx
> ex) : Dd 89 add shop page edit shop page css 
> 가게정보 수정 및 등록 css 수정, 
>  유저데이터 recoil 에서 받아오도록 설정
> 🐛 fix : Dd 89 add shop page edit shop page css 

- src/components/Post/Post.tsx
- src/components/pageComponents/NoticeDetail/NoticeDetailCard.tsx
- src/lib/utils/validation.ts
> #DD-95
>  이미지 쭈그러드는거랑 포스트카드의 시간부분 css 마진값 약간 수정습니다
> 💄style: post card 디자인 수정

- src/components/pageComponents/AddNotice/AddNoticeInput.tsx
- src/components/pageComponents/AddNotice/EditNoticeInput.tsx
- src/components/pageComponents/MyPage/MyPageInput.tsx
- src/lib/utils/validation.ts
- src/pages/404.tsx
- src/pages/_app.tsx
- tailwind.config.ts
DD92
1. 에러메세지 모달로 변경
2. 404에러 페이지 수정
3. 인풋 라우터 경로 설정
> ♻️ refactor input fixes

- src/components/pageComponents/AddShopPage/index.tsx
- src/lib/api/shopAPI.ts
- src/lib/utils/validation.ts
- src/recoil/atoms/AuthAtom.ts
>  Dd 94 refactor user state update
> recoil shopid 최신화 안되는거 수정
> 🐛hot fix: Dd 94 refactor user state update

- src/components/pageComponents/NoticeDetail/NoticeDetailModals.tsx
- src/hooks/useNoticeDetailCardButton.ts
>  #DD100
> 게스트일경우 로그인해주세요, 프로필등록안했을경우 내프로필을 등록해주세요 모달이 뜨도록변경했습니다
> ✨feat: 공고상세페이지 게스트 또는 프로필 등록안했을경우 처리

- src/components/Footer/footer.tsx
> 💄style: footer css 수정

- src/components/SortDropdown/DropdownBackdrop.tsx
- src/components/pageComponents/SearchPage/SearchPage.tsx
- src/hooks/useNoticeList.ts
- src/lib/api/noticeAPI.ts
(#99)
뒤로가기 가능하게 쿼리 적용
정렬 버튼 백드롭 투명하게 수정
검색 결과 없는 경우 처리
> refactor: search-improvements

- src/components/Modal/ModalPrimary.tsx
- src/components/Popup/Popup.tsx
- src/components/Popup/PopupsWrapper.tsx
- src/hooks/usePopup.ts
- src/recoil/atoms/PopupAtom.ts
- tailwind.config.ts
>  #DD-101
> 팝업이 페이드로 나타날때만 애니메이션을 걸어뒀었는데 사라질때도 애니메이션으로 fadeOut하도록 수정했습니다
setTimeOut이용해서작업하다보니까 .. 뭔가 맘에 안드는게 생기는데 어쩔 수 없는건가 싶기도하네요
주석으로 달아놨는데 멋진 해답을 아시는분은 코멘트 부탁드립니다 ... 
제완님이 말씀해주신 모달위에 띄우는거는 .. 노력해봤는데 일단안되서 요기까지만 PR올리고 자기전에 더 서치를 해보겠습니다 
🥹😭🥹😭 i can do it ㅜㅜ
스타일을 변경한건데 동적스타일이다보니까 로직이 변했어여 그치만 Style태그를 다는게 맞겠죠? .?
> 💄style: 팝업 fadeOut으로 사라지는 스타일 추가

- src/components/pageComponents/MyPage/MyPageInput.tsx
- src/hooks/useNoticeDetailCardButton.ts
- src/lib/api/alertAPI.ts
- src/lib/api/applicationAPI.ts
- src/lib/api/axiosInstance.ts
- src/lib/api/imageAPI.ts
- src/lib/api/noticeAPI.ts
- src/lib/api/shopAPI.ts
- src/lib/api/userAPI.ts
> DD-105-refactor-token.intercepctors
> token을 axiosinterceptors 로 이동
> ♻️refactor:  DD-105-refactor: token 인터셉터로 이동

- src/pages/shops/[shop_id]/index.tsx
> DD-110-fix: 내가게 에러 수정

- src/pages/shops/[shop_id]/notices/[notice_id]/index.tsx
> ♻️refactor: 공고상세페이지 재생성 시간 변경

- src/components/Footer/footer.tsx
- src/components/Post/PostCard.tsx
- src/pages/shops/[shop_id]/notices/[notice_id]/index.tsx
> #DD-111
> footer 마진 제거, post card 뱃지 위치 pc와 tablet 둘다 동일하게 설정 (태블릿에서도 overflow 경우가 있어서 변경했습니다🥹)
> 💄style: footer , post card 디자인 수정

- public/images/icon-arrow-sort-dropdown.svg
- src/components/SortDropdown/DropdownOptions.tsx
- src/components/Table/ActionButton.tsx
- src/styles/globals.css
DD-109-fix-svg-error
(#109)
- svg 설정에서 currentWidth 이런 식의 옵션은 잘못된 방법이었음
- 100%로 변경하여 에러 메세지 제거
(추가)
- 상수 변수명을 규칙에 따라 대문자로 수정
> 🐛 fix: svg-error, 변수명 수정

- src/components/AddShopPage/InputComponents.tsx
- src/components/pageComponents/AddShopPage/InputComponents.tsx
- src/components/pageComponents/AddShopPage/index.tsx
- src/components/pageComponents/NoticeDetail/RecentNoticeList.tsx
- src/components/pageComponents/NoticeList/CustomizedNoticeList.tsx
- src/components/pageComponents/NoticeList/NoticeListView.tsx
- src/components/pageComponents/ShopDetail/NoticesCardList.tsx
- tailwind.config.ts
DD-114-fix-pagination-cursor
#114
- 페이지네이션에 클릭하면 커서가 깜빡거리는게 보여서 제거함
- 클래스명에 공백 있는 부분 프로젝트 전체 검색해보면서 제거함
- 소소하게 호버 효과 추가
> 🐛fix : 페이지네이션 요소에 생키는 커서 제거, 클래스명 공백제거, 카드 호버 효과

- src/components/pageComponents/LoginSignUp/LoginSignUp.tsx
> 🐛fix: LoginSignup 바뀐 경로 수정

- next.config.mjs
- src/components/pageComponents/MyPage/MyPageInput.tsx
- src/hooks/useNoticeDetailCardButton.ts
- src/lib/api/alertAPI.ts
- src/lib/api/applicationAPI.ts
- src/lib/api/axiosInstance.ts
- src/lib/api/imageAPI.ts
- src/lib/api/noticeAPI.ts
- src/lib/api/shopAPI.ts
- src/lib/api/userAPI.ts
- src/lib/utils/FormatUtils.ts
- src/lib/utils/RemovePrefix.ts
> DD-117-fix-api-reset
>api 원복...
> 어떤 이유로 오류가 나는지는 알았는데 왜 오류인지는 아직 모르겠어요
> 🐛fix: Dd 117 fix api reset

- src/components/pageComponents/AddNotice/EditNoticeInput.tsx
- src/pages/shops/[shop_id]/notices/[notice_id]/editNotice.tsx
DD-116
1. 공고등록은 등록!
2. 공고편집은 편집!으로 네임 수정했습니다.
3. 편집할 때는 미리 데이터 불러와서 수정할 부분만 가능하게 바꿨어요.
_special thanks to 정민lee,,,🥇_
> ♻️  refactor: editnotice

- package-lock.json
- package.json
- src/components/Popup/Popup.tsx
- src/components/Post/Post.tsx
- src/components/Post/PostCard.tsx
- src/components/pageComponents/NoticeDetail/ApplicantsList.tsx
- src/components/pageComponents/NoticeDetail/NoticeDetailCard.tsx
- src/components/pageComponents/NoticeDetail/RecentNoticeList.tsx
- src/components/pageComponents/NoticeList/CustomizedNoticeList.tsx
- src/pages/_app.tsx
> 💄style: 포스트카드, 팝업 등 디자인 수정

- src/components/Table/ActionButton.tsx
- src/components/Table/EmployerTableBody.tsx
- src/components/Table/EmployerTableItem.tsx
- src/components/pageComponents/NoticeDetail/ApplicantsList.tsx
> 🐛fix: 지원자목록 상태변경 후 바로 업데이트 안되는 에러 수정

- src/components/pageComponents/NoticeList/CustomizedNoticeList.tsx
- src/components/pageComponents/ShopDetail/NoData.tsx
>  #DD-122
> 제목..이 내용.. nodata.tsx 에서 수정했습니다
> 💄style: 모바일에서 버튼 크기 수정 (overflow 이슈 해결)

- src/components/pageComponents/AddShopPage/index.tsx
- src/pages/_document.tsx
> ex) DD-123-feat-opengraph
> 오픈그래프만 추가했어요
> 📝 DOCS: DD-123-feat: 오픈 그래프 추가

- src/components/pageComponents/AddShopPage/index.tsx
- src/pages/_document.tsx
> Dd 123 feat opengraph
> 오픈그래프 이미지 변경
> 🐛fix: Dd 123 feat opengraph

- src/pages/shops/[shop_id]/index.tsx
> DD-126
가게주소와 사용자의 가게주소가 맞지않는경우 리다이렉트하는 코드를 추가했습니다.
> ♻️refactor: 유효성 검사 추가

- src/components/pageComponents/Loading/Loading.tsx
- src/components/pageComponents/NoticeList/NoticeListView.tsx
- src/components/pageComponents/SearchPage/SearchPage.tsx
- src/pages/_app.tsx
- src/pages/index.tsx
#127
DD-127-feat-optimize-loading-handling
발표 후 받은 피드백 useTransittion 적용해보기
로딩 아이콘을 로딩 이미지로 변경하기
- 로딩 컴포넌트화하여 재사용
> feat: 로딩 개선

- src/pages/_document.tsx
> DD-138
오랜만입니다 <head> 태그에 og image 경로 수정하겠습니다
> 🐛fix: head-icon 수정
